"""add table applicant with contacts and addresse

Revision ID: 16185f54eca3
Revises: 23da79fc46e4
Create Date: 2025-12-03 14:36:18.544071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from app.models_for_new_db_certs import TruncatedStringWithLog

# revision identifiers, used by Alembic.
revision: str = '16185f54eca3'
down_revision: Union[str, None] = '23da79fc46e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_applicant',
    sa.Column('idLegalSubject', sa.Integer(), nullable=False),
    sa.Column('idEgrul', sa.Integer(), nullable=True),
    sa.Column('idApplicantType', sa.Integer(), nullable=True),
    sa.Column('idLegalSubjectType', sa.Integer(), nullable=True),
    sa.Column('fullName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('shortName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idPerson', sa.Integer(), nullable=True),
    sa.Column('surname', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('firstName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('patronymic', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('headPosition', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('ogrn', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('ogrnAssignDate', sa.Date(), nullable=True),
    sa.Column('inn', TruncatedStringWithLog(length=255), nullable=False),
    sa.Column('kpp', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idLegalForm', sa.Integer(), nullable=True),
    sa.Column('regDate', sa.Date(), nullable=True),
    sa.Column('regOrganName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('addlRegInfo', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('isEecRegister', sa.Boolean(), nullable=True),
    sa.Column('transnational', sa.Boolean(), nullable=True),
    sa.Column('passportIssueDate', sa.Date(), nullable=True),
    sa.Column('passportIssuedBy', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('passportNum', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idPersonDoc', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_certificate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_certificate'], ['certificate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', name='uq_certificate_applicant_inn')
    )
    op.create_table('certificate_applicant_address',
    sa.Column('id_applicant', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idAddress', sa.Integer(), nullable=False),
    sa.Column('idAddType', sa.Integer(), nullable=True),
    sa.Column('idCodeOksm', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('oksmShort', sa.Boolean(), nullable=True),
    sa.Column('idSubject', sa.Integer(), nullable=True),
    sa.Column('idDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('flat', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('postCode', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('fullAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('gln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('uniqueAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('otherGln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('glonass', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_applicant'], ['certificate_applicant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_applicant_contact',
    sa.Column('id_applicant', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idContact', sa.Integer(), nullable=False),
    sa.Column('idContactType', sa.Integer(), nullable=True),
    sa.Column('value', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_applicant'], ['certificate_applicant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_applicant_contact')
    op.drop_table('certificate_applicant_address')
    op.drop_table('certificate_applicant')
    # ### end Alembic commands ###
