"""change idSubject in AddressMixin

Revision ID: 1738357b2b79
Revises: 99cbc74de455
Create Date: 2025-12-04 16:51:34.160449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from app.models_for_new_db_certs import TruncatedStringWithLog

# revision identifiers, used by Alembic.
revision: str = '1738357b2b79'
down_revision: Union[str, None] = '99cbc74de455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_applicant_address', 'idSubject',
               existing_type=sa.INTEGER(),
               type_=TruncatedStringWithLog(length=255),
               existing_nullable=True)
    op.alter_column('certificate_auth_address', 'idSubject',
               existing_type=sa.INTEGER(),
               type_=TruncatedStringWithLog(length=255),
               existing_nullable=True)
    op.alter_column('certificate_manufacturer_address', 'idSubject',
               existing_type=sa.INTEGER(),
               type_=TruncatedStringWithLog(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_manufacturer_address', 'idSubject',
               existing_type=TruncatedStringWithLog(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('certificate_auth_address', 'idSubject',
               existing_type=TruncatedStringWithLog(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('certificate_applicant_address', 'idSubject',
               existing_type=TruncatedStringWithLog(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
