"""add not null in applicant index

Revision ID: 1b031fff078a
Revises: 285821538e64
Create Date: 2025-12-03 15:32:20.100977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1b031fff078a'
down_revision: Union[str, None] = '285821538e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_certificate_applicant_inn_not_null', 'certificate_applicant', ['inn'], unique=True, mssql_where=sa.text('inn IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_certificate_applicant_inn_not_null', table_name='certificate_applicant', mssql_where=sa.text('inn IS NOT NULL'))
    # ### end Alembic commands ###
