"""delete False nullable in idObjectCertType

Revision ID: 23da79fc46e4
Revises: cf72b240891d
Create Date: 2025-12-03 10:14:15.409678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '23da79fc46e4'
down_revision: Union[str, None] = 'cf72b240891d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'idObjectCertType',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'idObjectCertType',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
