"""delete False nullable in inn applicant

Revision ID: 285821538e64
Revises: 16185f54eca3
Create Date: 2025-12-03 15:02:49.100174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '285821538e64'
down_revision: Union[str, None] = '16185f54eca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_applicant', 'inn',
               existing_type=sa.VARCHAR(length=255, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_applicant', 'inn',
               existing_type=sa.VARCHAR(length=255, collation='Cyrillic_General_CI_AS'),
               nullable=False)

