"""change Integer type to String in transnational in applicant

Revision ID: 32bb199319b8
Revises: e951fd86e42b
Create Date: 2025-12-08 14:45:07.895026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from app.models_for_new_db_certs import TruncatedStringWithLog

# revision identifiers, used by Alembic.
revision: str = '32bb199319b8'
down_revision: Union[str, None] = 'e951fd86e42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_applicant', 'transnational',
               existing_type=sa.INTEGER(),
               type_=TruncatedStringWithLog(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_applicant', 'transnational',
               existing_type=TruncatedStringWithLog(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
