"""add tables authority and manufacturer

Revision ID: 99cbc74de455
Revises: beed832ab9b0
Create Date: 2025-12-04 14:33:56.822666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from app.models_for_new_db_certs import TruncatedStringWithLog

# revision identifiers, used by Alembic.
revision: str = '99cbc74de455'
down_revision: Union[str, None] = 'beed832ab9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_certification_authority',
    sa.Column('idCertificationAuthority', sa.Integer(), nullable=False),
    sa.Column('fullName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('accredOrgName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('attestatRegNumber', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('attestatRegDate', sa.Date(), nullable=True),
    sa.Column('attestatEndDate', sa.Date(), nullable=True),
    sa.Column('idRal', sa.Integer(), nullable=False),
    sa.Column('ogrn', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idPerson', sa.Integer(), nullable=True),
    sa.Column('firstName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('surname', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('patronymic', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('prevAttestatRegNumber', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('prevIdRal', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_manufacturer',
    sa.Column('idLegalSubject', sa.Integer(), nullable=False),
    sa.Column('idEgrul', sa.Integer(), nullable=True),
    sa.Column('idLegalSubjectType', sa.Integer(), nullable=True),
    sa.Column('fullName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('shortName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idPerson', sa.Integer(), nullable=False),
    sa.Column('surname', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('firstName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('patronymic', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('headPosition', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('ogrn', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('ogrnAssignDate', sa.Date(), nullable=True),
    sa.Column('inn', TruncatedStringWithLog(length=255), nullable=False),
    sa.Column('kpp', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idLegalForm', sa.Integer(), nullable=True),
    sa.Column('regDate', sa.Date(), nullable=True),
    sa.Column('regOrganName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('addlRegInfo', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('isEecRegister', sa.Boolean(), nullable=True),
    sa.Column('transnational', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('passportIssueDate', sa.Date(), nullable=True),
    sa.Column('passportIssuedBy', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('passportNum', sa.Integer(), nullable=True),
    sa.Column('idPersonDoc', sa.Integer(), nullable=True),
    sa.Column('id_certificate', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_certificate'], ['certificate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', name='uq_certificate_manufacturer_inn')
    )
    op.create_table('certificate_auth_address',
    sa.Column('id_auth', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idAddress', sa.Integer(), nullable=False),
    sa.Column('idAddrType', sa.Integer(), nullable=True),
    sa.Column('idCodeOksm', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('oksmShort', sa.Boolean(), nullable=True),
    sa.Column('idSubject', sa.Integer(), nullable=True),
    sa.Column('idDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('flat', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('postCode', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('fullAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('gln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('uniqueAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('otherGln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('glonass', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_auth'], ['certificate_certification_authority.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_auth_contact',
    sa.Column('id_auth', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idContact', sa.Integer(), nullable=False),
    sa.Column('idContactType', sa.Integer(), nullable=True),
    sa.Column('value', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_auth'], ['certificate_certification_authority.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_manufacturer_address',
    sa.Column('id_manufacturer', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idAddress', sa.Integer(), nullable=False),
    sa.Column('idAddrType', sa.Integer(), nullable=True),
    sa.Column('idCodeOksm', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('oksmShort', sa.Boolean(), nullable=True),
    sa.Column('idSubject', sa.Integer(), nullable=True),
    sa.Column('idDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('flat', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('postCode', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('fullAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('gln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignDistrict', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignCity', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignLocality', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignStreet', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('foreignHouse', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('uniqueAddress', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('otherGln', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('glonass', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_manufacturer'], ['certificate_manufacturer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_manufacturer_contact',
    sa.Column('id_manufacturer', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idContact', sa.Integer(), nullable=False),
    sa.Column('idContactType', sa.Integer(), nullable=True),
    sa.Column('value', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_manufacturer'], ['certificate_manufacturer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_manufacturer_contact')
    op.drop_table('certificate_manufacturer_address')
    op.drop_table('certificate_auth_contact')
    op.drop_table('certificate_auth_address')
    op.drop_table('certificate_manufacturer')
    op.drop_table('certificate_certification_authority')
    # ### end Alembic commands ###
