"""fix idAddrType in AddressMixin

Revision ID: beed832ab9b0
Revises: 1b031fff078a
Create Date: 2025-12-04 12:59:44.619979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'beed832ab9b0'
down_revision: Union[str, None] = '1b031fff078a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_applicant_address', sa.Column('idAddrType', sa.Integer(), nullable=True))
    op.drop_column('certificate_applicant_address', 'idAddType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_applicant_address', sa.Column('idAddType', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('certificate_applicant_address', 'idAddrType')

    # ### end Alembic commands ###
