"""delete null in inn Certificate_Manufacturer

Revision ID: cd053ce60b0f
Revises: 1738357b2b79
Create Date: 2025-12-05 12:30:56.804388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'cd053ce60b0f'
down_revision: Union[str, None] = '1738357b2b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_manufacturer', 'inn',
               existing_type=sa.VARCHAR(length=255, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_manufacturer', 'inn',
               existing_type=sa.VARCHAR(length=255, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###
