"""delete False nullable in idCertScheme

Revision ID: cf72b240891d
Revises: d1c880f557c4
Create Date: 2025-12-02 17:01:46.308055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'cf72b240891d'
down_revision: Union[str, None] = 'd1c880f557c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'idCertScheme',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'idCertScheme',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###