"""make a certificate table

Revision ID: d1c880f557c4
Revises: e852f8731fd5
Create Date: 2025-12-01 15:32:05.495045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models_for_new_db_certs import TruncatedStringWithLog


# revision identifiers, used by Alembic.
revision: str = 'd1c880f557c4'
down_revision: Union[str, None] = 'e852f8731fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('idCertificate', sa.Integer(), nullable=False),
    sa.Column('idCertScheme', sa.Integer(), nullable=False),
    sa.Column('idObjectCertType', sa.Integer(), nullable=False),
    sa.Column('idCertType', sa.Integer(), nullable=False),
    sa.Column('isTs', sa.Boolean(), nullable=True),
    sa.Column('idProductSingleLists', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('awaitForApprove', sa.Boolean(), nullable=True),
    sa.Column('idStatus', sa.String(length=255), nullable=False),
    sa.Column('expiredInspectionControl', sa.Boolean(), nullable=True),
    sa.Column('editApp', sa.Boolean(), nullable=True),
    sa.Column('assignRegNumber', sa.Boolean(), nullable=True),
    sa.Column('number', TruncatedStringWithLog(length=255), nullable=False),
    sa.Column('certRegDate', sa.Date(), nullable=True),
    sa.Column('certEndDate', sa.Date(), nullable=True),
    sa.Column('idBlank', sa.Integer(), nullable=False),
    sa.Column('blankNumber', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('noSanction', sa.Boolean(), nullable=True),
    sa.Column('batchInspection', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('inspectionControlPlanDate', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('idSigner', sa.Integer(), nullable=True),
    sa.Column('idEmployee', sa.Integer(), nullable=True),
    sa.Column('firstName', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('surname', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('patronymic', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_annex',
    sa.Column('idAnnex', sa.Integer(), nullable=False),
    sa.Column('idType', sa.Integer(), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=True),
    sa.Column('pageCount', sa.Integer(), nullable=True),
    sa.Column('id_certificate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_certificate'], ['certificate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_has_tech_reglaments',
    sa.Column('id_certificate', sa.Integer(), nullable=False),
    sa.Column('idTechnicalReglaments', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_certificate'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_annexblank',
    sa.Column('idBlank', sa.Integer(), nullable=False),
    sa.Column('blankNumber', TruncatedStringWithLog(length=255), nullable=True),
    sa.Column('id_annexes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_annexes'], ['certificate_annex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_annexblank')
    op.drop_table('certificate_has_tech_reglaments')
    op.drop_table('certificate_annex')
    op.drop_table('certificate')
    # ### end Alembic commands ###
