"""add not null in manufaturer index

Revision ID: dc3a4a1aa5db
Revises: cd053ce60b0f
Create Date: 2025-12-05 13:24:01.391066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'dc3a4a1aa5db'
down_revision: Union[str, None] = 'cd053ce60b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_certificate_manufacturer_inn_not_null', 'certificate_manufacturer', ['inn'], unique=True, mssql_where=sa.text('inn IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_certificate_manufacturer_inn_not_null', table_name='certificate_manufacturer', mssql_where=sa.text('inn IS NOT NULL'))
    # ### end Alembic commands ###
