"""change bool type on Integer

Revision ID: e951fd86e42b
Revises: dc3a4a1aa5db
Create Date: 2025-12-08 14:37:53.951613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e951fd86e42b'
down_revision: Union[str, None] = 'dc3a4a1aa5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'isTs',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate', 'awaitForApprove',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate', 'expiredInspectionControl',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate', 'editApp',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate', 'assignRegNumber',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate', 'noSanction',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_applicant', 'isEecRegister',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_applicant', 'transnational',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_applicant_address', 'oksmShort',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_auth_address', 'oksmShort',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_manufacturer', 'isEecRegister',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('certificate_manufacturer_address', 'oksmShort',
               existing_type=mssql.BIT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_manufacturer_address', 'oksmShort',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate_manufacturer', 'isEecRegister',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate_auth_address', 'oksmShort',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate_applicant_address', 'oksmShort',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate_applicant', 'transnational',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate_applicant', 'isEecRegister',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'noSanction',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'assignRegNumber',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'editApp',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'expiredInspectionControl',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'awaitForApprove',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('certificate', 'isTs',
               existing_type=sa.Integer(),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
